src/Isotope80/Isotope.cs

Following suggestions from Paul in https://github.com/meddbase/isotope80/pull/1#issuecomment-698281607
Needed one additional SelectMany variation:
`public static Isotope<Env, C> SelectMany<Env, A, B, C>(this Isotope<Env, A> ma, Func<A, Isotope<B>> bind, Func<A, B, C> project)`

Add reader-monad behaviour V2

---

src/Isotope80/Isotope.cs

Adding some more options for controlling how and where the browser window appears when running tests.

Additional browser window control

---

samples/Samples.Console/Samples.Console.csproj
samples/Samples.UnitTests/Careers.cs
samples/Samples.UnitTests/Samples.UnitTests.csproj
src/Isotope80/Isotope.cs
src/Isotope80/Select.cs
src/Isotope80/WebElement.cs

Resolve issues with find

---

src/Isotope80/Internal/IsotopeInternal.cs

Fixed waitUntil bug from previous commit (causing click method malfunction).

Fix in waitUntil bug

---

src/Isotope80/Isotope.cs
src/Isotope80/WebDriverSelect.cs

Add support for the use of the Safari web driver.

Safari web driver support

---

src/Isotope80/Isotope.cs

Close current tab method added

Add a close current tab

---

src/Isotope80/Internal/IsotopeInternal.cs
src/Isotope80/Isotope.cs

waitUntilClickable sometimes failed on stale element error.

Wait until clickable bug fix

---

samples/Samples.Console/Samples.Console.csproj
samples/Samples.UnitTests/Careers.cs
samples/Samples.UnitTests/Samples.UnitTests.csproj
src/Isotope80/Isotope80.csproj

Language Ext and chrome driver updated.

Lang ext bump

---

samples/Samples.Console/Samples.Console.csproj
samples/Samples.UnitTests/Careers.cs
samples/Samples.UnitTests/Samples.UnitTests.csproj
src/Isotope80/Isotope.cs

New functions added: swtichToFrame and switchToParentFrane.
Used to switched to iframes to gain control.

Switch to frame

---

samples/Samples.UnitTests/Careers.cs
src/Isotope80/Isotope80.csproj

Selenium has been updated to ver. 4.12.2

Selenium update

---

src/Isotope80/Isotope80.csproj

Selenium updated to ver. 4.13.1

Selenium updated to ver. 4.13.1

---

src/Isotope80/Isotope80.csproj

Selenium has been updated to ver. 4.15.0

Selenium update to ver. 4.15.0

---

samples/Samples.Console/Meddbase.cs
samples/Samples.Console/Program.cs
samples/Samples.UnitTests/AlertHandling.cs
samples/Samples.UnitTests/Careers.cs
samples/Samples.UnitTests/EvalTests.cs
samples/Samples.UnitTests/LoggingTests.cs
samples/Samples.UnitTests/SequenceTests.cs
src/Isotope80/Assertions.cs
src/Isotope80/Internal/IsotopeInternal.cs
src/Isotope80/Isotope.Selectors.cs
src/Isotope80/Isotope.cs
src/Isotope80/IsotopeAsync_A.cs
src/Isotope80/IsotopeAsync_Env_A.cs
src/Isotope80/IsotopeSettings.cs
src/Isotope80/Isotope_A.cs
src/Isotope80/Isotope_Env_A.cs
src/Isotope80/Select.cs
src/Isotope80/WebDriverSelect.cs
src/Isotope80/WebElement.cs

Added alert / prompt handling functions:
- acceptAlert
- dismissAlert
- getAlertText
- sendKeysToAlert
- isAlertPresent
Added moveTo functions:
- moveToElement
- moveToLocation
- moveByOffset
New unit test added for alert handling.
Ability to start driver with options (eg. for disabling default automatic alert dismiss function in chrome driver).
Removed support for IE.
Cleaned up unused usings.

Alert handling

---

src/Isotope80/Isotope.cs

Driver service

---

src/Isotope80/Isotope.cs

It's possible to extract the page source and title.

Page details

---

src/Isotope80/Internal/IsotopeInternal.cs
src/Isotope80/Isotope80.csproj
src/Isotope80/Select.cs
src/Isotope80/WebElement.cs

- value attribute added to WebElement
- overwrite() method updated to fix occasional select all on page
- error message corrected for moveByOffset()

Webelement update

---

src/Isotope80/Isotope80.csproj

Selenium update to ver. 4.20.0

Selenium update to ver. 4.20.0

---

src/Isotope80/Isotope.cs

Two methods added:
- getting number of currently opened tabs
- getting position of currently opened tab

Window handles

---

src/Isotope80/Isotope.cs
src/Isotope80/Isotope80.csproj

Selenium updated to ver.  4.25.0
getBrowserLogs added - to get logs from console

Selenium update + getBrowserLogs

---

src/Isotope80/Isotope80.csproj

Selenium update to ver. 4.27.0

Selenium update to ver. 4.27.0

---

src/Isotope80/Isotope80.csproj

Selenium update to ver. 4.28.0

Selenium update to ver. 4.28.0

---

src/Isotope80/Select.cs
src/Isotope80/WebElement.cs

Attribute 'title' added to WebElement.

Attribute title added to WebElement.

---

src/Isotope80/Isotope80.csproj

Selenium updated to ver. 4.34.0

Selenium update to ver. 4.34.0
